"""Initial schema - analyses, source_credibility, community_feedback

Revision ID: 6b526df0458b
Revises: 
Create Date: 2025-10-26 04:38:13.160482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b526df0458b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instagram_url', sa.String(length=500), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('processing_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_instagram_url'), 'analyses', ['instagram_url'], unique=False)
    op.create_index(op.f('ix_analyses_post_id'), 'analyses', ['post_id'], unique=True)
    op.create_table('source_credibility',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('bias_rating', sa.String(length=50), nullable=True),
    sa.Column('reliability_rating', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('community_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('vote_type', sa.Enum('ACCURATE', 'MISLEADING', 'FALSE', name='votetype'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_feedback_analysis_id'), 'community_feedback', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_community_feedback_ip_hash'), 'community_feedback', ['ip_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_feedback_ip_hash'), table_name='community_feedback')
    op.drop_index(op.f('ix_community_feedback_analysis_id'), table_name='community_feedback')
    op.drop_table('community_feedback')
    op.drop_table('source_credibility')
    op.drop_index(op.f('ix_analyses_post_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_instagram_url'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
